# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AppCine' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AppCine
  pod 'youtube-ios-player-helper', '~> 1.0'

  target 'AppCineTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AppCineUITests' do
    # Pods for testing
  end

end
